import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header/page.js";
import Footer from "./components/footer/page.js";

const gilroySemiBold = localFont({
  src: "../../public/fonts/Gilroy-SemiBold.ttf",
  variable: "--font-gilroy-semibold",
  weight: "600", // Corrected to an array
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gilroySemiBold.variable} antialiased`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
